#build settings
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme 
title: Classic Mode for Wikipedia
description: a Firefox add-on to get the classic Wikipedia interface and layout back.
